= Quarkus Redoc

include::./includes/attributes.adoc[]

This extension provides https://redocly.com/redoc/[Redoc] API documentation for your Quarkus application. Redoc is an open source tool for generating documentation from OpenAPI (formerly Swagger) definitions.

This extension uses **Redoc 3.0** and supports all Redoc Community Edition (CE) configuration options.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.redoc:quarkus-redoc` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.redoc</groupId>
    <artifactId>quarkus-redoc</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

Once installed, Redoc CE will be available at `/q/redoc` in dev and test modes. Simply navigate to that URL to view your API documentation - or press on the corresponding link in dev-ui.

You can activate Redoc CE for production mode by configuring:

[source,properties]
----
quarkus.redoc.always-include=true
----

== Changing the Download URLs

By default, this extension configures Redoc CE to show download URLs for the OpenAPI document in both JSON and YAML format.

You can disable them completely using the following configuration.

[source,properties]
----
quarkus.redoc.hide-download-buttons=true
----

You can also override the default provided download URLs with your own. For example, if your API is about users, you could change the URLs as follows.

[source,properties]
----
quarkus.redoc.download-urls[0].title=User API JSON
quarkus.redoc.download-urls[0].url=/q/openapi.json
quarkus.redoc.download-urls[1].title=User API YAML
quarkus.redoc.download-urls[1].url=/q/openapi.yaml
----

You can provide as many download URLs as you want.
See also how to configure indexed properties in the Quarkus documentation: https://quarkus.io/guides/config-reference#indexed-properties

== Logo

Your custom logo can be displayed above the sidebar.
See the configuration values starting with `quarkus.redoc.extensions.x-logo.` for more information.

This works by customizing the OpenAPI document generated by quarkus-smallrye-openapi. An additional `x-logo` vendor extension - from Redoc CE - is added to the info object.

== Tag Groups

Often, as applications grow large, so does the amount of OpenAPI tags. OpenAPI tags are used to sort operations into categories.

Tag groups, a Redocly CE feature, allows you to group tags of the same kind together.

Let's imagine your application has the tags: Order, Order Import, Masterdata, User, User Import

We can configure our application to group these tags as follows.

[source,properties]
----
quarkus.redoc.extensions.x-tag-groups[0].name=Order Management
quarkus.redoc.extensions.x-tag-groups[0].tags=Order, Order Import
quarkus.redoc.extensions.x-tag-groups[1].name=User Management
quarkus.redoc.extensions.x-tag-groups[1].tags=User, User Import
----

This configuration generates the following groups:

[source]
----
* Order Management
** Order
** Order Import
* User Management
** User
** User Import
* Other
** Masterdata <1>
** Schemas <2>
----
<1> Notice how we did not specify a tag group for Masterdata? Every tag which is *not* assigned to a category is automatically put into a group called "Other".
You can change the name of this group using:
[source,properties]
quarkus.redoc.extensions.x-tag-groups-ungrouped-name=Anything else

<2> The `Schemas` tag comes from the `quarkus.redoc.schema-definitions-tag-name` configuration property, and is also put into the `Other` group. You can explicitly assign this tag to another group using the previously shown `quarkus.redoc.extensions.x-tag-groups.tags` option.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-redoc.adoc[leveloffset=+1, opts=optional]
