= Quarkus Redoc

include::./includes/attributes.adoc[]

This extension provides https://redocly.com/redoc/[Redoc] API documentation for your Quarkus application. Redoc is an open source tool for generating documentation from OpenAPI (formerly Swagger) definitions.

This extension uses **Redoc 3.0** and supports all Redoc Community Edition (CE) configuration options.

== Features

**Specify Download URLs**
By default, this extension configures Redoc CE to show download URLs for the OpenAPI document in both JSON and YAML format.

You can disable them completely using the following configuration.

[source,properties]
----
quarkus.redoc.hide-download-buttons=true
----

You can also override the default provided download URLs with your own. For example, if your API is about users, you could change the URLs as follows.

[source,properties]
----
quarkus.redoc.download-urls[0].title=User API JSON
quarkus.redoc.download-urls[0].url=/q/openapi.json
quarkus.redoc.download-urls[1].title=User API YAML
quarkus.redoc.download-urls[1].url=/q/openapi.yaml
----

You can provide as many download URLs as you want.
See also how to configure indexed properties in the Quarkus documentation: https://quarkus.io/guides/config-reference#indexed-properties

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.redoc:quarkus-redoc` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.redoc</groupId>
    <artifactId>quarkus-redoc</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

Once installed, Redoc will be available at `/q/redoc` in dev and test modes. Simply navigate to that URL to view your API documentation.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-redoc.adoc[leveloffset=+1, opts=optional]
